### ISSUE TITLE
Can't install pod

### ISSUE THREAD

**Issue by g3k000** [tomknig/TOMSSuggestionBar#5]
Can't install the pod - dies on a dependency.  Is there anything I can do to get it to run?  Am I doing something wrong?

Analyzing dependencies
Downloading dependencies
Installing AFIncrementalStore (0.5.1)
Installing AFNetworking (1.3.4)
Installing InflectorKit (0.0.1)
Installing TOMSCoreDataManager (0.1.4)
[!] /usr/bin/git fetch origin tags/0.1.4 2>&1

fatal: Couldn't find remote ref tags/0.1.4

fatal: The remote end hung up unexpectedly

**Comment by tomknig** [comment]
Hi,

it seems that i forgot to tag the release 0.1.4 of the core data manager. I have added the tag and pushed the changes.
Please let me know if it works for you.

Cheers,
Tom

**Comment by g3k000** [comment]
It works now.  Thanks.
