### ISSUE TITLE
How can I integrate your Suggestion Tool Bar in Custom Keyboard Extension ?

### ISSUE THREAD

**Issue by KrLikeblue** [tomknig/TOMSSuggestionBar#6]
Hello,

Your code works well in project without extension.

I have created one keyboard extension and I want to put suggestion bar inside keyboard extension.

How can I achieve it ?

Thanks.

**Comment by tomknig** [comment]
Hi, I did not yet try that by myself. I will have to experiment a little bit and let you know if I get something to work... Thanks & Cheers!

**Comment by KrLikeblue** [comment]
I am trying, but suggestion bar is not appearing on top of custom keyboard somehow. I am trying to find that solution.

**Comment by KrLikeblue** [comment]
Hi,

Below method is not calling while I enter some text via custom keyboard:
- (void)textChanged:(UIControl<UITextInput> *)textInputView

It is going in below method perfectly:
- (BOOL)subscribeTextInputView:(UIControl<UITextInput> *)textInputView
  toSuggestionsForAttributeNamed:(NSString *)attributeName
               ofEntityNamed:(NSString *)entityName
                inModelNamed:(NSString *)modelName
  {
  if ([textInputView respondsToSelector:@selector(setInputAccessoryView:)]) {
      textInputView.autocorrectionType = UITextAutocorrectionTypeNo;
      textInputView.toms_suggestionBar = self;
  
  ```
  self.suggestionBarView.attributeName = attributeName;
  self.suggestionBarView.entityName = entityName;
  self.suggestionBarView.modelName = modelName;
  ```
  
  //        self.suggestionBarView.delegate = self;
  //        self.suggestionBarView.dataSource = self;
      self.textInputView = textInputView;
  
  ```
  [self.textInputView performSelector:@selector(setInputAccessoryView:)
                           withObject:self.suggestionBarView];
  
  [self.textInputView addTarget:self
                         action:@selector(textChanged:)
               forControlEvents:UIControlEventEditingChanged];
  
  return YES;
  ```
  
  }
  return NO;
  }

Any idea ?

**Comment by tomknig** [comment]
Hm no sorry, couldn't figure out what the problem is. I hope you find a solution that works for you and please let us know when you did so.

**Comment by Dennisdezhangaho** [comment]
Seems like you dont work it out, guys.

**Comment by tomknig** [comment]
Hey @Dennisdezhangaho, sorry that you seem to be running into this problem too. I am unfortunately not actively working on this project anymore and don't think I can help here. Please feel free to open a pull request for fixing a bug or adding documentation if you like. Otherwise, a similar and actively developed project exists here: https://github.com/lexrus/LTMorphingLabel
Hope that helps.
